export { default as About } from './About/About'
export { default as Home } from './Home/Home'
export { default as Faqs } from './Faqs/Faqs'
export { default as Guide } from './Guide/Guide'
export { default as Smile } from './Smile/Smile'